---

- name: Check if Secret exist
  uri: 
    url: "{{ hc_vault_server }}/v1/sys/mounts"
    headers: 
      X-Vault-Token: "{{ hc_vault_token }}"
  register: r_check_secret

- debug: 
    var: r_check_secret.json['database/']

- name: Create MSSQL secret engine
  uri:
    url: "{{ hc_vault_server }}/v1/sys/mounts/database"
    validate_certs: no
    method: POST
    headers: 
      X-Vault-Token: "{{ hc_vault_token }}"
    body: '{"type": "database" }'
    body_format: json
    status_code: 204
  # no_log: yes
  when: r_check_secret.json['database/'] is not defined
   
    
- name: Configure MSSQL secret engine
  uri:
    url: "{{ hc_vault_server }}/v1/database/config/{{ ansible_hostname }}_{{ mssql_db }}"
    validate_certs: no
    method: POST
    headers: 
      X-Vault-Token: "{{ hc_vault_token }}"
    body: "{{ lookup('template', 'templates/hc_mssql_settings.j2') }}"
    body_format: json
  # no_log: yes


- name: Create a read/write role
  uri:
    url: "{{ hc_vault_server }}/v1/database/roles/readonly"
    validate_certs: no
    method: POST
    headers: 
      X-Vault-Token: "{{ hc_vault_token }}"
    body: "{{ lookup('template', 'templates/hc_mssql_roles.j2') }}"
    body_format: json
    status_code: 200, 204
  # no_log: yes


